parameters:
- name: download_folder
  type: string
- name: download_filename
  type: string
- name: url
  type: string
- name: sha512
  type: string

steps:
- task: Cache@2
  inputs:
    key: '"download" | "${{ parameters.sha512 }}" | "${{ parameters.download_filename }}" | "${{ parameters.url }}"'
    path: "${{ parameters.download_folder }}"
  displayName: Source cache ${{ parameters.download_folder }}/${{ parameters.download_filename }}

- powershell: |
    . "azure-pipelines/lib.ps1"

    $d = "${{ parameters.download_folder }}"
    New-Item -ItemType Directory -Force -Path $d
    Get-FileFromInternet "${{ parameters.url }}" "${{ parameters.sha512 }}" "$d\${{ parameters.download_filename }}"

  displayName: Download source ${{ parameters.download_folder }}/${{ parameters.download_filename }}
